enemyPath={
	paths:pth_monkey0
};
instance_create_layer(x,y,"instances",obj_monkey,enemyPath);
struct_set(enemyPath,"paths",pth_monkey1);
instance_create_layer(x,y,"instances",obj_monkey,enemyPath);
struct_set(enemyPath,"paths",pth_monkey2);
instance_create_layer(x,y,"instances",obj_monkey,enemyPath);
struct_set(enemyPath,"paths",pth_monkey3);
instance_create_layer(x,y,"instances",obj_monkey,enemyPath);
struct_set(enemyPath,"paths",pth_monkey4);
instance_create_layer(x,y,"instances",obj_monkey,enemyPath);
struct_set(enemyPath,"paths",pth_monkey5);
instance_create_layer(x,y,"instances",obj_monkey,enemyPath);

struct_set(enemyPath,"paths",pth_bird0);
instance_create_layer(x,y,"instances",obj_bird,enemyPath);
struct_set(enemyPath,"paths",pth_bird1);
instance_create_layer(x,y,"instances",obj_bird,enemyPath);
struct_set(enemyPath,"paths",pth_bird2);
instance_create_layer(x,y,"instances",obj_bird,enemyPath);
struct_set(enemyPath,"paths",pth_bird3);
instance_create_layer(x,y,"instances",obj_bird,enemyPath);
struct_set(enemyPath,"paths",pth_bird4);
instance_create_layer(x,y,"instances",obj_bird,enemyPath);

struct_set(enemyPath,"paths",pth_fly0);
instance_create_layer(x,y,"instances",obj_fly,enemyPath);
struct_set(enemyPath,"paths",pth_fly1);
instance_create_layer(x,y,"instances",obj_fly,enemyPath);
struct_set(enemyPath,"paths",pth_fly2);
instance_create_layer(x,y,"instances",obj_fly,enemyPath);
struct_set(enemyPath,"paths",pth_fly3);
instance_create_layer(x,y,"instances",obj_fly,enemyPath);
struct_set(enemyPath,"paths",pth_fly4);
instance_create_layer(x,y,"instances",obj_fly,enemyPath);