sentences = [
	"left click to start",
    "Good morning, world!",
    "Today is another great day!",
    "Ah!",
    "Wait, today is the day of sacrifice to the deity!",
    "This is not a good day, it's the day my poor disabled brother is to be sacrificed...",
    "How could I, as his brother, witness him being taken into the mouth of the sacred mountain to be consumed by the deity? No, I can't let that happen. I have to go help him. I'll try to persuade him to escape.",
    "Brother, brother, are you there?",
    "Today's sacrifice is you, you'll be killed alive by the villagers!",
    "Why are you still here and leisurely standing around? ",
    "If I were you, I'd already be thinking of ways to escape!",
    "Oh hi, brother, good morning!",
    "Of course, I know I'm tonight's chosen one, but I don't intend to flee.",
    "Isn't this the thousand-year-old tradition of our village?",
    "Sacrificing one villager for the peace of the whole village for a year, I'm not afraid of this sacrifice.",
    "Look at me, I've already lost one hand, unable to do normal work anymore.",
    "No one in this world respects a man with only one hand.",
    "Perhaps the only time left in my life to hear cheers for me will be when I, as a sacrifice, am cheered by the villagers at the altar during the ritual.",
    "This is my destiny, from the moment I was informed by the village chief last year, or even earlier when I lost an arm at the age of 8, I could foresee my fate as a disabled person.",
    "To die so heroically, I have no regrets!",
    "But how can I bear to lose my dearest, poor brother? How can I bear to let that awful deity do such cruel things...",
    "Brother, there's nothing to argue about!",
    "If you can't even respect the sacred traditions of our village passed down for thousands of years, at least respect my will, my life!",
    "Actually, my brother is right.",
    "I should indeed respect his wishes, perhaps that's the only way to make him happy.",
    "But how can I betray my own stance?",
    "I also bear some responsibility for my poor brother's tragic fate.",
    "I still remember when we were 8 years old, and we went to the zoo.",
    "If it weren't for my carelessness, accidentally triggering that 'be careful or you'll hurt your brother' machine, how could my brother have lost an arm?",
    "How could he have become a sacrifice to the deity?",
    "You awful deity!!!",
    "I will stop you from killing my brother!!!",
    "But then, thinking about it, I seem to know nothing about this deity except for the sacrificial ritual.",
    "Perhaps I should ask Father if there's any way to save my brother.",
    "After all, he's the eldest elder in the village.",
    "Father! Father!",
    "Why are you also so calm?",
    "Today is the day those ignorant villagers and that horrible deity are going to kill my brother, why are you so indifferent?",
    "My son, why have you come?",
    "Of course, I know today is that day.",
    "But how can an ordinary person like me change the will of a deity?",
    "I had to come!",
    "Father, you're the oldest and wisest elder.",
    "Don't you know if there's any way to save my brother, to let him live?",
    "My dear son, though I am of considerable age, my knowledge of this fearsome deity is also scant, merely passed down through the mouths of elderly people in the past.",
    "My understanding of this deity is almost the same as yours, but indeed there is said to be a method to save your brother, however...",
    "Father, please tell me quickly!",
    "I must save my brother!",
    "Very well, my dear son.",
    "Actually, this sacrificial ritual doesn't necessarily have to take place at midnight, that's just the final deadline for sacrifice to the deity.",
    "But even if there's just one day left, who would willingly end their precious life prematurely?",
    "My child, do you remember the big sign we used to see when we gazed at the sacred mountain in our childhood?",
    "I once witnessed a young man, similar to you and your brother, unable to accept reality and starting the ritual prematurely.",
    "And the number on the sign changes as the sacrificial ritual progresses.",
    "That ritual didn't happen only at midnight.",
    "But Father, what good does that do?",
    "I don't want my brother to die, not even a moment sooner!",
    "The deity never designated who should be sacrificed, that's decided by villagers.",
    "The deity doesn't care who gets sacrificed.",
    "So, as long as someone sacrifices themselves for my brother at the mountain pass before midnight, my brother won't have to be sacrificed?",
    "My naive child, no one would end their life for another person. Moreover, who dares to defy the villagers' chosen one?",
    "I'm feeling a bit tired now, I'm going to rest, my child.",
    "What does villagers matter? I fear not even the deity.",
    "My brother's wrongful fate is my doing, so let me rewrite it.",
    "I'm sorry, brother!",
    "I'm sorry, Father!!",
    "I will challenge this merciless deity!",
	"......",
	"......",
	"......",
	"......",
	"?????????????????????????",
	"????????????????????????????????????????",
	"......",
	"......",
	":D",
	"END"
]
current_sentence_index = 0; 
display_text = "";

